server:
  port: 8091

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    org.hibernate: ERROR
    org.apache.http: DEBUG

kafka:
  bootstrap-address: "localhost:9092"

csv:
  csvConfigList:
    -
      folder-path: /Users/thendriks/projects/ditect/csvs
      delimiter: ";"
      quote: "\""
    -
      folder-path: /Users/thendriks/projects/ditect/csvs2
      delimiter: "|"
      quote: "\""

