server:
  port: 8091

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    com.howtodoinjava: DEBUG
    org.hibernate: ERROR

kafka:
  bootstrap-address: "localhost:9092"

csv:
  folder-path: /Users/thendriks/projects/ditect/csvs
  delimiter: ";"
  quote: "\""